apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: nodeapp
  newName: blgianinis/nodeapp
  newTag: 16fc651344ec18eb1df7db5bfae5569931f37333
