apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: nodeapp

images:
- name: goapp
  newName: blgianinis/nodeapp
  newTag: 9516daca4ed168a55cff61b2cd720f91a22626cb
- name: nodeapp
  newName: blgianinis/nodeapp
  newTag: v1
